####### MAIN CONFIG #######
baseURL = "https://maremotocafe.com/"
title = "Maremoto Café & Cocktail"
defaultContentLanguage = "es"
languageCode = "es"

enableRobotsTXT = true
enableGitInfo = false

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr", "en"]

####### DEFAULT PARAMETERS ######
[params]
logo = "images/logo.png"
author = "Mario Ortiz Manero"
google_analytics_id = "UA-162662877-2"
post_share = true

###### LANGUAGE-DEPENDENT CONTENT ######
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
description = "Maremoto Café & Cocktail en Zaragoza"
tags = "bar,pub,copas,cafeteria,cocktails,zaragoza,cafes,desayunos,brunch,zumos,reposteria,bocadillos,centro,aragon"
home = "Inicio"
copyright = """
Página desarrollada por [Mario Ortiz Manero](https://github.com/marioortizmanero).  
*Basado en [gethugothemes](https://gethugothemes.com), licencia [Attribution 3.0 Unported](https://creativecommons.org/licenses/by/3.0/).*
"""

####### MAP #######
[params.map]
enable = true
place = "Maremoto Café & Cocktail"

####### SCROLL TO TOP #######
[params.scrollToTop]
enable = true
where = "#carta"
txt = "Ir a Carta"
icon = "las la-angle-double-up"

####### OLD BROWSER WARNING #######
[params.oldBrowser]
enable = true
txt = "Tu navegador web es demasiado antiguo. Para ver la página correctamente, instala un navegador moderno:"
icon = "las la-exclamation-triangle"

####### SOCIAL NETWORKS #######
[[params.social]]
icon = "lab la-facebook-f"
link = "https://www.facebook.com/maremotocafeandcocktail/"

[[params.social]]
icon = "lab la-twitter"
link = "https://twitter.com/maremotocafe"

[[params.social]]
icon = "lab la-instagram"
link = "https://www.instagram.com/maremotocafeandcocktail"

####### NAVIGATION #######
[[menu.main]]
name = "Glovo"
URL = "glovo"
weight = 1

[[menu.main]]
name = "Carta"
URL = "carta"
weight = 2

[[menu.main]]
name = "Contacto"
URL = "contact"
weight = 3
