####### MAIN CONFIG #######
baseURL = "https://maremotocafe.com/"
title = "Maremoto Café and Cocktail"
theme = "meghna-hugo"
defaultContentLanguage = "es"
languageCode = "es"

enableRobotsTXT = true
enableGitInfo = false

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

####### DEFAULT PARAMETERS ######
[params]
logo = "images/logo.png"
description = "Maremoto Café and Cocktail"
author = "Mario Ortiz Manero"
google_analytics_id = "UA-162662877-2"
post_share = true

###### LANGUAGE-DEPENDENT CONTENT ######
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
home = "Inicio"
copyright = "copyright &copy; 2019 [gethugothemes](https://gethugothemes.com) all right reserved"

####### MAP #######
[params.map]
enable = true
place = "Maremoto Café & Cocktail"

####### SCROLL TO TOP #######
[params.scrollToTop]
enable = true
where = "#carta"
txt = "Ir a Carta"

####### SOCIAL NETWORKS #######
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/maremotocafeandcocktail/"

[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/maremotocafe"

[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/maremotocafeandcocktail"

####### NAVIGATION #######
[[menu.main]]
name = "Carta"
URL = "carta"
weight = 1

[[menu.main]]
name = "Contacto"
URL = "contact"
weight = 2
