####### MAIN CONFIG #######
baseURL = "http://maremotocafe.com/"
title = "Maremoto Café and Cocktail"
theme = "meghna-hugo"
defaultContentLanguage = "es"
languageCode = "es"

enableRobotsTXT = true
enableGitInfo = false

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

####### DEFAULT PARAMETERS ######
[params]
logo = "images/logo.png"
description = "Maremoto Café and Cocktail"
author = "Mario Ortiz Manero"
google_analytics_id = "UA-162662877-2"
post_share = true

###### LANGUAGE-DEPENDENT CONTENT ######
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
home = "Inicio"
copyright = "copyright &copy; 2019 [gethugothemes](https://gethugothemes.com) all right reserved"

# google map
[params.map]
enable = true
# ID obtained by sharing the location and then selecting "Embed map"
gmap_id = "!1m14!1m8!1m3!1d11925.881421582186!2d-0.878576!3d41.6455785!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xfad6f08736f1f129!2sMaremoto%20Caf%C3%A9%20%26%20Cocktail!5e0!3m2!1sen!2ses!4v1589193455388!5m2!1sen!2ses"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

####### NAVIGATION #######
[[menu.main]]
name = "About Us"
URL = "about"
weight = 1

[[menu.main]]
name = "Service"
URL = "services"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Team"
URL = "team"
weight = 4

[[menu.main]]
name = "Pricing"
URL = "pricing"
weight = 5

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

#### external / static link ####
[[menu.static]]
name = "Themefisher"
URL = "https://themefisher.com/"
weight = 8
